### ISSUE TITLE
Random server crash(s)

### ISSUE THREAD

**Issue by CrownZeroGaming** [VORPCORE/VORP-AdminMenu#14]
When contacting Blue, he said to first post the issue in Vorp-Inventory but I guess its a VORP-AdminMenu issue?
I have linked the error below in the link;

[https://prnt.sc/26npzus](url)

**Comment by Local9** [comment]
Please try the attached server dll, this will either fix it, or print out a new error, hopefully not crashing the server.

[vorpadminmenu_sv.net.zip](https://github.com/VORPCORE/VORP-AdminMenu/files/7997958/vorpadminmenu_sv.net.zip)

**Comment by CrownZeroGaming** [comment]
> 
I started the new update, I will keep you posted with what happens.

**Comment by Local9** [comment]
Reading the ban logic, I can see issues with it, and will be refactoring how that is done tomorrow. Hopefully what is committed works for you.

**Comment by Local9** [comment]
@CrownZeroGaming any updates?

**Comment by CrownZeroGaming** [comment]
Haven't had any crash's since the build you sent over.

**Comment by Local9** [comment]
Closing as issue fixed
