### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by NeoGaming22** [VORPCORE/VORP-AdminMenu#2]
Script is causing fatal errors with the latest update and causing the server to have memory leaks. Its in ban management section thats all that it says in the logs

**Comment by Artzalez** [comment]
can you post a screenshot please @NeoGaming22

**Comment by NeoGaming22** [comment]
![image](https://user-images.githubusercontent.com/48037518/89284358-a8582a00-d61c-11ea-9cbb-d648fe7dc777.png)

**Comment by Artzalez** [comment]
check db and paste screenshot from table bans
