### ISSUE TITLE
Fatal error when a blocked user tries to join.

### ISSUE THREAD

**Issue by BulgaRpl** [VORPCORE/VORP-AdminMenu#6]
![image](https://user-images.githubusercontent.com/69915160/97320493-261f8080-186e-11eb-9d7a-91919fe6556f.png)

Today I banned the first person on my server, and now when he tries to join I get such errors.

**Comment by rubi216** [comment]
Did you ban him using the right syntax?

**Comment by rubi216** [comment]
Found here: https://github.com/VORPCORE/VORP-AdminMenu

**Comment by BulgaRpl** [comment]
/ban ID 12H Reason

It is normally entered as a 12hour ban in the database and this player cannot connect. Well, but there is such an error when he try.
